disabled_rules:
  - force_try
  - multiple_closures_with_trailing_closure
  - force_cast
  - cyclomatic_complexity
  - type_name
  - file_length
  - function_body_length
  - type_body_length
opt_in_rules:
  - number_separator
analyzer_rules:
  - unused_declaration
  - unused_import
number_separator:
  minimum_length: 5
line_length: 200
identifier_name:
  max_length:
    warning: 100
    error: 100
  min_length:
    warning: 2
    error: 2
  validates_start_with_lowercase: false
  allowed_symbols:
    - '_'
  excluded:
    - 'x'
    - 'y'
    - 'a'
    - 'b'
    - 'x1'
    - 'x2'
    - 'y1'
    - 'y2'
