name: Feature request
description: Suggest an idea for the app
title: 'Feature: '
labels: 'feature'
assignees: ''
body:
- type: textarea
  attributes:
    label: Issue that this suggestion fixes
    description: A clear and concise description of the issue as you see it.
    placeholder: "e.g., I'm always frustrated when…"
  validations:
    required: true
- type: textarea
  attributes:
    label: Solution description
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
